[package]
name = "anglo-saxon-dict-parser"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.79"
env_logger = "0.11.1"
log = "0.4.20"
scraper = "0.18.1"
tantivy = "0.21.1"
reqwest = "0.11.23"
url = "2.5.0"
